name: Build & Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17
      - uses: actions/checkout@v2
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew assemble
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew
      - name: test
        run: ./gradlew test