name: Build & Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/chechout@v2
        with:
          fetch-depth: '500'
      - name: build
        run: ./gradlew assemble
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: test
        run: ./gradlew test